name: Sync To Gitee

on: [ push, delete, create ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:Italink/ModernGraphicsEngineGuide.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:Italink/ModernGraphicsEngineGuide.git
